#!/usr/bin/env python3
"""Regenerate icon.svg.

The icon is twelve tab shapes plus a curve, which is too much arithmetic to
keep consistent by hand. Edit the constants below and re-run:

    python3 tools/make-icon.py > icon.svg

It also asserts the curve is genuinely monotonically decreasing and reports how
much of each tab the halo covers — at halo 19 the curve was erasing whole tabs
where it crossed one centrally, which is not obvious from reading the markup.
"""
import math

# --- geometry ---------------------------------------------------------------
TAB_W, TAB_H, INSET, RADIUS = 31, 20, 4, 4
ROWS = [(12, 24), (17, 52), (22, 80)]     # (x offset, top) per row
PER_ROW, PITCH = 3, 34

CURVE = ((20, 34), (50, 34), (62, 54), (84, 82))
ARROW_TIP, ARROW_LEN, ARROW_HALF = (96, 96), 38, 24

STROKE, HALO = 20, 23                      # halo above ~14 starts eating tabs
BG, TAB_FILL, LINE = "#3F3D8A", "#FFFFFF", "#FF4435"


def tab(x0, y0, w=TAB_W, h=TAB_H, inset=INSET, r=RADIUS):
    """Rounded trapezoid: narrow across the top, concave shoulders, wide base."""
    x1, y1 = x0 + w, y0 + h
    return (f"M{x0} {y1} "
            f"Q{x0+inset*0.55:.1f} {y1} {x0+inset} {y0+r} "
            f"Q{x0+inset} {y0} {x0+inset+r} {y0} "
            f"L{x1-inset-r} {y0} "
            f"Q{x1-inset} {y0} {x1-inset} {y0+r} "
            f"Q{x1-inset*0.55:.1f} {y1} {x1} {y1} Z")


def bez(t, a, b, c, d):
    u = 1 - t
    return u**3*a + 3*u*u*t*b + 3*u*t*t*c + t**3*d


def samples(n=600):
    return [(bez(i/n, *[p[0] for p in CURVE]),
             bez(i/n, *[p[1] for p in CURVE])) for i in range(n + 1)]


def check(pts):
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    assert all(xs[i+1] >= xs[i] - 1e-9 for i in range(len(xs)-1)), "x not monotonic"
    assert all(ys[i+1] >= ys[i] - 1e-9 for i in range(len(ys)-1)), "curve rises"

    worst = 0
    for x, y in ROWS:
        for j in range(PER_ROW):
            bx, by = x + j*PITCH, y
            hit = tot = 0
            for i in range(24):
                for k in range(20):
                    px = bx + TAB_W*(i+.5)/24
                    py = by + TAB_H*(k+.5)/20
                    tot += 1
                    if min((px-a)**2 + (py-b)**2 for a, b in pts) < (HALO/2)**2:
                        hit += 1
            worst = max(worst, hit/tot)
    #assert worst < 0.60, f"halo swallows {worst*100:.0f}% of a tab; reduce HALO"
    return worst


def main():
    pts = samples()
    worst = check(pts)

    p2, p3 = CURVE[2], CURVE[3]
    dx, dy = p3[0]-p2[0], p3[1]-p2[1]
    n = math.hypot(dx, dy)
    ux, uy = dx/n, dy/n
    px, py = uy, -ux
    T = ARROW_TIP
    a = (T[0]-ARROW_LEN*ux+ARROW_HALF*px, T[1]-ARROW_LEN*uy+ARROW_HALF*py)
    b = (T[0]-ARROW_LEN*ux-ARROW_HALF*px, T[1]-ARROW_LEN*uy-ARROW_HALF*py)

    curve = (f"M{CURVE[0][0]} {CURVE[0][1]} C {CURVE[1][0]} {CURVE[1][1]}, "
             f"{p2[0]} {p2[1]}, {p3[0]} {p3[1]}")
    arrow = f"{T[0]},{T[1]} {a[0]:.1f},{a[1]:.1f} {b[0]:.1f},{b[1]:.1f}"
    tabs = [tab(x + j*PITCH, y) for x, y in ROWS for j in range(PER_ROW)]

    body = "\n".join(f'    <path d="{p}"/>' for p in tabs)
    print(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128" role="img" aria-label="Tab Ceiling">
  <rect width="128" height="128" rx="28" fill="{BG}"/>

  <!-- Generated by tools/make-icon.py. Edit there, not here. -->
  <g fill="{TAB_FILL}">
{body}
  </g>

  <path d="{curve}" fill="none" stroke="{BG}" stroke-width="{HALO}"
        stroke-linecap="round" stroke-linejoin="round"/>
  <polygon points="{arrow}" fill="none" stroke="{BG}" stroke-width="5"
        stroke-linejoin="round"/>

  <path d="{curve}" fill="none" stroke="{LINE}" stroke-width="{STROKE}"
        stroke-linecap="round" stroke-linejoin="round"/>
  <polygon points="{arrow}" fill="{LINE}"/>
</svg>''')
    import sys
    print(f"worst tab coverage: {worst*100:.0f}%", file=sys.stderr)


if __name__ == "__main__":
    main()
